# Generated by Django 5.2 on 2025-04-26 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_total', models.PositiveIntegerField(blank=True, null=True)),
                ('occupied', models.PositiveIntegerField(blank=True, null=True)),
                ('free', models.PositiveIntegerField(blank=True, null=True)),
                ('local', models.BooleanField(default=0)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('raiting', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('locals', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kino.locals')),
            ],
        ),
    ]
